github_user: ENC[AES256_GCM,data:kC2TaF8=,iv:qidYojcxjV7VOFAN6i2XJhkvfJV9DKF017brNP6K4bY=,tag:g1YKLAjDZSDvnEiO1xr/DQ==,type:str]
github_token: ENC[AES256_GCM,data:tGzPg1xW8PT5dMVsAM5jc/5b6S/+GKXsKe+8Qa0KG7DNFZGy26mZvhy/lILYKu1iN8/ymt2pmo83zCVpgdXI/Q4n4OkdixO/sVIREVz9htIrF8f+n9NweW1eDKu9,iv:E2KR+u0Vt3TBaP6UnZvqCoS4OtrL6wr/nvXnTDgB/2c=,tag:MWrObje8PVb8PWfyKXEvHQ==,type:str]
sops:
    age:
        - recipient: age16dmx502nhcs3vd05uj2h36372v6mnk0t0j7a6p0ufr9qa8gt739sr7ccw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV21MamV4dHUxNmRLcStj
            QktNMDNFUjY1TmNsblJDdTZ5Z0lCby9mZFhjCmQ2VWFydkFoY0E1R2FtWjF3dTBR
            NTN0RHZnSjR2bENadThqK0FlZVlJS3MKLS0tIEV5czJZOG1POUxHUWs2WmtJTnlI
            RGxCT2ROZXlBL3h6b0hVaDR0N2xJVlUK+GEAVF5F7FKNbFit2sX4od2+RcPZ32zY
            N9UyJyMoQhybduuErKBbJ+RUm9/g6w+3ivolwq/Pdhu3KRB8FMNcGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T12:27:38Z"
    mac: ENC[AES256_GCM,data:zuwoTIPYGHAdNkJtNyn/2c/WSXnuHNe++s5AjJ82j9IMZqXf3VgnZfaPZGgl9jyD528NgpTt4o09Ty3gM+KN1m2eYlp7jkVK26TlcPCxl9NitgEBma7WB8xN790E7oBoU+7d/FnrtRyJOzy5cqqPpl7y1eTc1+CXpNEVJHiXsns=,iv:AiUo/gPSqQHDsq9E9kyctlYXfny4sLqYsQXfSYO0++k=,tag:z9LuYoHBofdSyP19038ggA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
